# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_song_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('action', models.CharField(max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
