# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_song_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
