# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20170918_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.CharField(max_length=11),
        ),
    ]
