# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_songhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='songhistory',
            name='action',
            field=models.CharField(choices=[('Added', 'Added'), ('Updated', 'Updated'), ('Deleted', 'Deleted')], max_length=16),
        ),
    ]
