# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20170920_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='songhistory',
            name='link',
            field=models.CharField(max_length=11),
        ),
    ]
