# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0007_playlist_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together=set([('title', 'user')]),
        ),
    ]
