# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_auto_20170921_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='thumb_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
